### ISSUE TITLE
returning a view vs a redirect?

### ISSUE THREAD

**Issue by philyuska** [susanBuck/e2-fall19#110]
Is there a rule of thumb to follow when deciding to return a view versus a redirect?
It seems to me that returning a redirect after processing input from a form is the appropriate action. Are there situations when returning a view is more appropriate, if using a multi-part form perhaps?

**Comment by susanBuck** [comment]
If you're handling a form submitted with POST, you're pretty much always going to do a redirect afterwards. Otherwise, if you just return a view, the user can refresh the page, triggering the form data to be processed again.

With GET requests, this is not typically a concern, because GET requests should just be retrieving data.

**Comment by philyuska** [comment]
Ah, i didn't make that connection. Thank you!

**Comment by susanBuck** [comment]
np!
