### ISSUE TITLE
findById error - not returning data

### ISSUE THREAD

**Issue by Janeece** [susanBuck/e2-fall19#114]
When I try to dump the results of findById, I get a Fatal Error. However, I was able to get the Id. 
Why is this happening?
```php

$gameId = $this->app->param('id');

        //dump($gameId);

        $game = $this->app->db()->findById('games', $gameId);
        
        dump($game);
```
I also can't get my form validation to work. I think it because the players choice is removed when the button is submitted. I can't figure out why the players choice is being removed.

I just published to production and nothing is showing on the history page.
Here is my github repository. https://github.com/Janeece/e2/tree/master/p4

**Comment by susanBuck** [comment]
## Issue 1 - fatal syntax error
According to my tests, here are the details of your fatal error:

```
Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: syntax error, unexpected ',', expecting ']' in /Users/Susan/Sites/hes/dwa-bash/students/e2/p4/cache/a1a7c77a62fec39ecdeaa0662be8b97c7aa57ce8.php:15 
```

Following the strategies discussed here - [Debugging views](https://github.com/susanBuck/e2-fall19/issues/86) - I can track this error down to `/views/game.blade.php` on this line:

```php
{{ $game['id', 'choices', 'prizePick', 'results', 'player', 'created_at']}}
</p>
```

This is not valid syntax for accessing multiple elements in an array, which is why the fatal error is indicating it's a syntax error.

You could do this:
```php
{{ $game['id'] }} 
{{ $game['choice'] }}
{{ $game['prizePick'] }}
[...etc..]
```

Or this:

```php
{{ $game['id'] . $game['choice'] . $game['prizePick'] }}
```

## Issue 2 - form validation
Regarding form validation not working...
When I tested it (by submitting the form without selecting an option) it appeared to work as expected:

![image](https://user-images.githubusercontent.com/237711/70850865-eec60200-1e5c-11ea-9afd-06e2a7f8e707.png)

Can you elaborate on how it's not working/not doing what you're expecting?


## Issue 3 - Nothing showing on the history page
Are there rows in the database table to show history?
These rows will either come via your seeds, or by playing the game.

When I try to play the game locally I got the following error
![image](https://user-images.githubusercontent.com/237711/70850907-59773d80-1e5d-11ea-909f-bc6994fc756f.png)

This error occurs because you created the table with a  field `'created_at' => 'timestamp',` but you don't populate that field when inserting the game data:

```php
    $data = [
            'choices' => $choice,
            'prizePick' => $prizePick,
            'results'=> $results,
            'player' => $player,  
        ];

//insert players choice into the database
$this->app->db()->insert('games', $data);
```

**Comment by Janeece** [comment]
Thank you for responding so quickly.

You are getting different errors then I am.

Issue 1: Fatal Syntax Error
I made the changes to the array as directed.
I am still getting the same error message:
*Fatal error*: Uncaught Error: Call to undefined method
E2\Database::findById() in
C:\xampp\htdocs\e2\p4\app\Controllers\AppController.php:92 Stack trace: #0
C:\xampp\htdocs\e2\p4\vendor\susanbuck\e2core\src\App.php(219):
App\Controllers\AppController->game() #1
C:\xampp\htdocs\e2\p4\public\index.php(15): E2\App->route() #2 {main}
thrown in *C:\xampp\htdocs\e2\p4\app\Controllers\AppController.php* on line
*92*

Issue 2: Validation Error
The form doesn't hold the value. It looks like it sends the error even if
I've selected a button.  I never get the message saying I won or lost.

Issue 3: Nothing showing on History page
I do have data in the database and it shows when I run it locally. But when
I run it in production, the history is blank.
[image: image.png]
[image: image.png]
[image: image.png]
Thank again for your help,
Janeece

**Comment by sg7788** [comment]
> When I try to dump the results of findById, I get a Fatal Error. However, I was able to get the Id.
> Why is this happening?

I was getting this error, too - it looked like the function, `findById`, was maybe accidentally deleted from the version of the dependency I had, so I ran `composer update` in my local environment and the `findById` function was included again in the latest version.

**Comment by susanBuck** [comment]
Hi @Janeece - FYI - cloning your project again to test locally on my end. Will report back with what I find!

**Comment by Janeece** [comment]
I’ve got it working in my local environment. But I have errors in
production.
Working those now.
Thanks for your help!!!

**Comment by susanBuck** [comment]
Did some more debugging -

I see you addressed my _created_at_ note above with this:

```php
'created_at' => $timestamp,
```

This is on the right track, but is problematic because `$timestamp` is never defined, which produces an error when run. 

I started to address this by defining `$timestamp` using [PHP's date function](https://www.php.net/manual/en/function.date.php), but I remembered that because the MySQL data type is `timestamp`, it should actually generate the timestamp for you. Note how for **Default** it says `current_timestamp():`

![image](https://user-images.githubusercontent.com/237711/70935379-08f31200-200e-11ea-8e1a-3411ba5df133.png)

Given this, a correction to my above suggestion: You shouldn't actually need to specify a value for the `created_at` field. Apologies for that misleading advice!

After I removed trying to insert a value into `created_at`, I kept running into this error:

```
Incorrect integer value: '' for column `student`.`games`.`results`
```

The issue here was you were trying to insert values like `true` and `false` into the `results` field. This is a logical thing to do, because you did create that field as a *boolean* field in your migration.

However, you'll recall that when we set the MySQL data type to *boolean* it actually sets it to `tinyint(1)`:

![image](https://user-images.githubusercontent.com/237711/70935050-50c56980-200d-11ea-85e8-f5792a0bb9c3.png)

This means it's expecting an integer value that is 1 digit long. So in this case, we need to convert `true` to `1` and `false` to `0`.

In your seeds I accomplished this with a ternary operator:
```php
$game = [
            'choices' => $faker->randomDigit,
            'prizePick' => $faker->word,
            'results' => $faker->boolean ? 1 : 0, # <----- 
            'player' => $faker->word,
        ];
```

And in AppController@saveNewGame I accomplished it by changing this:

```php
 
        if ($prizePick == 'Car') {
            $results = true;
        } else {
            $results = false;
        }
```

To this:
```php
        if ($prizePick == 'Car') {
            $results = 1;
        } else {
            $results = 0;
        }
```

Or even better, we could reduce those 5 lines down to 1 using a ternary operator again:

```php
$results = ($prizePick == 'Car') ? 1 : 0;
```

After the above changes, I was able to choose a door, submit the form, and get results like "You lost" or "You won".

I could also observe that my results were being stored in the database:

![image](https://user-images.githubusercontent.com/237711/70935585-8028a600-200e-11ea-8817-2de660288924.png)

As I was writing this reply, I got notified of your last reply indicating it was working locally but not on production. I don't want to dig too much further into this before we sync up on where we're at- **so let me know what the current issue is that you're having and we can continue to debug this.** 👍

**Comment by Janeece** [comment]
Thanks!! I’ll implement your suggestions and then get back to you.

**Comment by susanBuck** [comment]
Ok! If it's helpful, here's the current status of your `AppController.php` file in my local copy:

```php
<?php
namespace App\Controllers;

class AppController extends Controller
{
    /**
     *
     */
    public function index()
    {
        $choice = $this->app->old('choice');
        $player = $this->app->old('player');

        dump($player);
        return $this->app->view('index', ['player' => $player]);
    }
  
    // This is to save new games
    public function saveNewGame()
    {
        $this->app->validate([
            'choice' => 'required',
        ]);
        
        $player = null;
        $prize = ['Donkey', 'Donkey', 'Car'];
        $choice = $_GET['choice'];
        $choices = $choice;
        $prizePick = ($prize[rand(0, 2)]);
        $results = ($prizePick == 'Car') ? 1 : 0;
        $player = ($results) ? 'won' : 'lost';
       
        $data = [
            'choices' => $choice,
            'prizePick' => $prizePick,
            'results'=> $results,
            'player' => $player,
        ];

        // insert players choice into the database
        $this->app->db()->insert('games', $data);

        // redirect home to show the results
        $this->app->redirect('/', ['choices' => $data['choices']]);
        $this->app->redirect('/', ['player' => $data['player']]);
    }

    // This is for the game history
    public function games()
    {
        $games = $this->app->db()->all('games');
          
        return $this->app->view('games', ['games' => $games]);
    }

    // This is for the individual game details
    public function game()
    {
        $gameId = $this->app->param('id');
        $game = $this->app->db()->findById('games', $gameId);
        return $this->app->view('game', ['game' => $game]);
    }
}
```

**Comment by Janeece** [comment]
IT WORKS!!!
After I implemented the code you sent. It works in production.
Thank you !!!

**Comment by susanBuck** [comment]
Excellent! : ) Going to close this thread out, but feel free to start another one if you run into any more issues!
