### ISSUE TITLE
Round Details not populating

### ISSUE THREAD

**Issue by janenycxo** [susanBuck/e2-fall19#116]
Hello again,

Can someone help me figure this out.....

Project 4 (http://p4.janenycxo.me/) is about complete, though I'm wondering why my round details are not displaying like it does in P3 (http://p3.janenycxo.me/).

I have included the code for round details/form results which are entered on the-index.blade.php file and it looks as it should, but when you enter the individual result page (p4.janenycxo.me/result) 
or id result page (http://p4.janenycxo.me/result?id=8) I would like for it to show the results of the player's choices.

as always, Thank you!!

**Comment by susanBuck** [comment]
FYI Cloning your repo locally and taking a look at this now. Will write again when I have more details.

**Comment by susanBuck** [comment]
Expectation: When we visit `/result?id=8` we should see the details for result #8.

The method triggered by this route is:

```
 public function result()
    {
        $id = $this->app->param('id');
          
        dump($id);
        return $this->app->view('result');
    }
```

In this method, you get the id from the route param, and you return the `result` view.

**What you're missing, though, is a query to the database to get the information for that result.**

Then, with that information, you need to pass it to View, where you'll need to add code to display the result info.

Right now, this is what your view looks like:
![image](https://user-images.githubusercontent.com/237711/70952122-559d1400-2033-11ea-8944-e27f35054985.png)

**Comment by janenycxo** [comment]
I have been trying. i am struggling to get the project site up to par and I have managed to get the round details to populate on the page but now the results.blade.php and result.blade.php return with an error. i focused on getting the details of the rounds, now that they are working nothing else seems to work. i pulled another all-nighter and will keep plugging away but i need to get ready for the day. Can you advise on what I need to do to bring the site back?
[P4 issues.docx](https://github.com/susanBuck/e2-fall19/files/3972749/P4.issues.docx)

**Comment by susanBuck** [comment]
FYI Looking at this now.

**Comment by susanBuck** [comment]
To help you troubleshoot, I first cloned your project locally to test it and debug it there.

Your seeds/migrations failed to run with the following error:

```
^ "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'student.selection' doesn't exist"
```

This happens because in your migration you create a table `selections` (plural) but in your seeds you attempt to insert data into a table `selection` (singular).

After I fixed that, I then got this error:

```
~/Sites/hes/dwa-bash/students/e2/p4 (master) ! $ php console App fresh
^ "Executing App\Commands\AppCommand@fresh"
^ "It works! You invoked your migrate command."

Notice: Undefined variable: player1 in /Users/Susan/Sites/hes/dwa-bash/students/e2/p4/app/Commands/AppCommand.php on line 25

Notice: Undefined variable: player1 in /Users/Susan/Sites/hes/dwa-bash/students/e2/p4/app/Commands/AppCommand.php on line 33

Notice: Undefined variable: player1 in /Users/Susan/Sites/hes/dwa-bash/students/e2/p4/app/Commands/AppCommand.php on line 25

Notice: Undefined variable: player1 in /Users/Susan/Sites/hes/dwa-bash/students/e2/p4/app/Commands/AppCommand.php on line 33

[...etc...]
```

Looking at your seed method, this error makes sense because `$player1` is never defined:

![image](https://user-images.githubusercontent.com/237711/71017786-28994180-20c5-11ea-9f18-eb93bf1064d8.png)

To fix, I defined `$player1`:

![image](https://user-images.githubusercontent.com/237711/71017839-41a1f280-20c5-11ea-8720-c3cc5ff87538.png)

Then your migrations and seeds worked without error:

```
~/Sites/hes/dwa-bash/students/e2/p4 (master) ! $ php console App fresh
^ "Executing App\Commands\AppCommand@fresh"
^ "It works! You invoked your migrate command."
^ "It works! You invoked your seed command."
```

Next, I visited the site in the browser. I choose a breed, clicked the submit button, and it sends me to `/save-new-result` with a blank white page .

![image](https://user-images.githubusercontent.com/237711/71017934-7b72f900-20c5-11ea-9393-4a60f75a8abd.png)

Looking at the corresponding `saveNewResult` method, this makes sense because nothing is done after the results are inserted into the database - there's no redirect, no returning of a view, etc.

![image](https://user-images.githubusercontent.com/237711/71017985-96456d80-20c5-11ea-8d95-2338d5190eef.png)

This outcome seems different from what you described above/what I'm seeing in the Word doc you shared. Have there been changes to your code base since you shared that info?

**Comment by susanBuck** [comment]
FYI I'm on Zoom if you want to do a screenshare and walk through this in real time https://harvard-dce.zoom.us/j/6503342434

**Comment by janenycxo** [comment]
I am so very thankful for your time and walking me through P4.
