### ISSUE TITLE
Retrieve the value for radio button

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e2-fall19#119]
How can I retrieve the value for radio buttons?

```html
    <input type="radio" value="rock" id="rock" name="choice">
    <label for="rock">Rock</label>
    <input type="radio" value="paper" id="paper" name="choice">
    <label for="paper">Paper</label>
    <input type="radio" value="scissors" id="scissors" name="choice">
    <label for="scissors">Scissors</label>
```
In AppController:
```php
$choice = $this->app->input('choice');
```
Returns null

**Comment by conornap** [comment]
I have a similar setup and this works fine for me. Does 'choice' not equal the value?

**Comment by anyav77** [comment]
Yes, the script in the controller doesn't pick up the value, or it doesn't see the name.
It returns null. 
When I enter the default fallback, it returns the fallback:
```$choice = $this->app->input('choice', 'test');```
returns test

**Comment by susanBuck** [comment]
Hi @anyav77 - FYI looking at your code repo now to reproduce the error.

**Comment by susanBuck** [comment]
To debug this, I updated your `process` method so the first and last thing it did was simply to dump the contents of the `$_POST` request:

```php
public function process()
{
    dd($_POST);
    # ... etc...
}
```

This always resulted in an empty array:

![image](https://user-images.githubusercontent.com/237711/70952656-e0cad980-2034-11ea-86ab-6fed6541a455.png)

Given this, I took a closer look at your form to try and understand why this was happening.

I checked that each radio button had a `name` attribute and I compared it against a working example, but found notable differences.

Next, I studied your form open tag:
```
<form method="POST" action="process/">
```

The `method="POST"` looked correct.

The `action="process/"` stood out though, specifically the path of `process/`. I'm used to seeing the path as `/process` or just `process`, but not `process/`.

Sure enough, when I changed it to `/process` or `process`, then the `$_POST` request was getting data:

![image](https://user-images.githubusercontent.com/237711/70952844-88480c00-2035-11ea-81e9-b42a3962d9d0.png)

**So that's the fix, but the question remains of why `process/` didn't work.** 

I did some research on this ([ref](https://stackoverflow.com/a/42926359/59479)) and here's what I think is happening:

You'll note that when you submit the form to `process/` it actually ends up landing on `process` (no trailing slash). This happens because Apache interprets `process/` as a request to a directory, and for security purposes it doesn't want to allow access to that so it does a 301 redirect to `process`.

It's in this redirect that the POST data gets lost.

So when we fix the form to submit to `process` or `/process` no redirect happens and the form data is left intact.

**Comment by anyav77** [comment]
Thank you!  It worked.

I was doing the troubleshooting on my end, and I got it to work.  I thought it was a mismatch between 
```
action="/process"
```
and the route
```php
 '/process' => ['AppController', 'process'],
```
Thank you for explaining it!
