### ISSUE TITLE
"No configured push destination" when synchronizing to Github

### ISSUE THREAD

**Issue by jeremiahazurin** [susanBuck/e2-fall19#121]
The message I'm receiving on terminal is: 

```
$ git push
fatal: No configured push destination.
Either specify the URL from the command-line or configure a remote repository using

    git remote add <name> <url>

and then push using the remote name

    git push <name>
```

For some reason stopped syncing. How do I find a push destination? Is it ```git push -u origin master```? If it helps, I typed ```git init``` when reviewing the lecture view from last week, which I know i'm not supposed to do. An error I get is:
```
error: failed to push some refs to 'git@github.com:jeremiahazurin/e2.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```
I've tried:
```git remote add origin```
```git push -u origin master```

Lastly, I can't connect to my production server. I receive an ```Permission denied (publickey).``` error. How do I fix this?

**Comment by jeremiahazurin** [comment]
Also, I tried looking for help and am stuck on this page:

<img width="697" alt="Screen Shot 2019-12-17 at 00 40 59" src="https://user-images.githubusercontent.com/16971379/70967947-e856a680-2065-11ea-942a-ea84829f3ead.png">
How do I exit out of this?

**Comment by jeremiahazurin** [comment]
Now everything I'm trying is in red. Is that a bad thing?

<img width="697" alt="Screen Shot 2019-12-17 at 00 47 07" src="https://user-images.githubusercontent.com/16971379/70968298-c27dd180-2066-11ea-9a88-ca1407459037.png">

**Comment by susanBuck** [comment]
In this reply, I'll focus on the first issue you listed. For the purposes of clarity, please create a separate post for the production server *Permission denied (publickey)* issue.

I've studied the output you shared in the above screenshot and there's a lot of things going on.

Three notes in reply to some of the specific questions you asked about:

+ You said you ran `git init` - in which directory specifically did you run this? Within `/e2/` or within `/e2/p4`?
+ `git remote add origin` by itself is an incomplete command; it needs to be followed by the path to the origin, e.g. `git remote add origin git@github.com:username/reponame.git`
+ `git push -u origin master` will push commits _and_ set `origin` to be the default remote/destination for pushes, and `master` to be the default branch for pushes.

**How to fix things...**

To straighten things out, the first thing I'd like to do is assess what your remote origin is currently set to. To do this, run the command `git remote show origin` from within your `/Applications/XAMPP/xamppfiles/htdocs/e2` directory. Share the complete output (including the command) in your reply.

Here's an example of what it should look like (with my username instead of yours, of course):

```bash
/Applications/XAMPP/xamppfiles/htdocs/e2 (master)  $ git remote show origin
* remote origin
  Fetch URL: git@github.com:susanBuck/e2.git
  Push  URL: git@github.com:susanBuck/e2.git
  HEAD branch: master
  Remote branch:
    master tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
```

**Comment by jeremiahazurin** [comment]
Thank you! I ran ```git init``` from ```/e2/p4```!

Also, here's the screenshot when I ran ```git remote show origin```
![Screen Shot 2019-12-17 at 12 02 30](https://user-images.githubusercontent.com/16971379/71017762-1c14e900-20c5-11ea-8c91-114bc19fd305.png)

**Comment by susanBuck** [comment]
Since it seems we're both online now, can we connect via Zoom to do a screenshare regarding this issue?

My Zoom URL is https://harvard-dce.zoom.us/j/6503342434

**Comment by susanBuck** [comment]
Issue resolved via Zoom, so closing this thread. Feel free to re-open/start a new thread if it happens again.

**Comment by jeremiahazurin** [comment]
Hi, all:

So the ```git push``` error was solved for a short while but for some reason came back when I was in my ```/e2/p4``` directory! I haven't tried deploying since we Zoom'd. Still getting the following error:
```
fatal: The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin master
```
However, I tried doing it again in ```/e2``` (ie not ```/e/p4```) and it seemed to work. Will it matter? Everything is in sync in ```/e2/p4``` so I guess this is ok? Just want to make sure

**Comment by susanBuck** [comment]
Because you mentioned running `git init` in your p4 directory, it likely became its own git repo nested in the e2 git repo, but it was never fully configured which is why you keep getting these errors when running git commands within `/e2/p4`.

To address this:

1) Remove the `.git` folder I'm assuming is in `/e2/p4`. This will effectively undo the `git init` you did earlier.
2) Run all git related commands from the root of the repository at `/e2`, not within `/e2/p4`

**Comment by jeremiahazurin** [comment]
Thank you! To clarify, this is ```git rm .git``` within ```/e2/p4/```, right?

**Comment by susanBuck** [comment]
We want to do an actual deletion, so we can use the `rm` command. Because it's a directory we add `-rf` to make it delete it recursively.

So, within `e2/p4` run:

```bash
rm -rf .git
```

**Comment by jeremiahazurin** [comment]
Thank you!
