### ISSUE TITLE
Git/Terminal Back Up Question

### ISSUE THREAD

**Issue by MPVaccaro** [susanBuck/e2-fall19#23]
# Preparing for Computer Failure

I am working from a mid-2015 Macbook Pro.  I will be traveling a lot for work during the next two months.  I back up my entire hard drive regularly using ```SuperDuper```. 

It took me 2 days to set up  ```Terminal, Git, GitHub,``` and ```Digital Ocean```. 

It seems to me that I can only work on my class projects from _**this particular computer**_.

* If my computer is lost, stolen or crashes, what happens to my ```ssh security codes```? 

* Can my git/terminal and ssh settings be recreated from the backup? 

* Will I be locked out of managing my Digital Ocean e2 project until I recreate all the settings on a new computer?  

* Are there _**best practices**_ for backing up these settings to prevent downtime during computer loss?

I certainly don't expect problems, but I want to be prepared.

**Comment by susanBuck** [comment]
Good questions, and always good to be prepared. My answers below...

## "If my computer is lost, stolen or crashes, what happens to my ssh security codes?"

**If your computer is stolen**, your SSH key pairs are effectively compromised. The thief could log into any system/server that you've stored a public key on, that you have a corresponding private key for your computer.

As an average user, I would not worry about this. If someone is stealing my computer it's because they want to sell it, not because they're trying to hack into my servers.

If it was a computer belonging to a company that, for example, worked on some highly profitable/desirable target servers, the risks are higher. 

**If your computer crashes**, and you have no backup, you've lost the private key and the SSH pair is no longer useful. In that case, I'd set up a new computer, generate new key pairs, and store the new corresponding public key on my server.

To get access to the server to do this, I'd have to rely on some backup way to get access. One way is via DigitalOcean's web console. Or, if you worked for a company, a colleague could use their access to the server to add an SSH key for you.

## "Can my git/terminal and ssh settings be recreated from the backup?"

It depends on how you do your backups (I'm not familiar with how SuperDuper works).

On my Mac I use TimeMachine, which stores snapshots of my computer - this includes, files, software, configurations, etc. If I set up a new computer from a TimeMachine snapshot, it should be almost exactly the same, and all my git/terminal/ssh settings/configs should transfer.

If you use a more manual backup system, you'd want to be sure that your git/terminal/ssh settings/configs are included in the backup.


## "Will I be locked out of managing my Digital Ocean e2 project until I recreate all the settings on a new computer?"

Yes and no. You won't be completely locked out - as you  can always access your DO server via their web console (described in these [supplemental notes](https://hesweb.dev/e2/notes#/appendix/permission-denied)). But working via the web console is only for emergencies and is typically used just to get you back into your server if you get locked out. You wouldn't want to actually edit your project files via the web console.
So to get back on track with editing project files, you would want to recreate all the settings on a new computer.

## "It took me 2 days to set up Terminal, Git, GitHub, and Digital Ocean. It seems to me that I can only work on my class projects from this particular computer."

I know it seems like a lot of configs/setup the first few times you do it, but - like most things - the more you become comfortable with it, the simpler it seems.

If you wanted or needed to set up a new computer, don't hesitate to reach out. I'd be happy to walk through the steps with you to expedite the process.

## "Are there best practices for backing up these settings to prevent downtime during computer loss?"

For me, the answer to this question is a backup system like TimeMachine that creates a snapshot of my entire system.

**Comment by MPVaccaro** [comment]
# Show Hidden Files on a Mac

Thank you for this detailed answer!

I am greatly relieved to have this information.  I checked on-line, and "SuperDuper" does make a "clone" of the hard drive.  I will confirm this when I an home and I will check to see if the hidden files are backed up.

I researched on-line and found the following method to ```show hidden files``` on Macs.  _This only works on Macs running OS10.12 (Sierra) or higher._

**To find hidden SSH and Git Config files:**

1. Go to your Mac ```Home``` folder (with the icon of the house).
2. Press ```command``` + ```shift``` + ```.``` 
3. You will see the ```.gitconfig``` file
4. You will see the ```.ssh``` folder
5. Click the ```.ssh folder``` and you will see its contents, which include ```config files``` and ```keys``` that you have created.

Using this method, you will be able to see what you have on your computer and you will also be able to confirm that you have these folders and files included in any back-ups that you have made.

**Comment by susanBuck** [comment]
Excellent, glad to hear SuperDuper is giving you a full clone! 

I'm going to go ahead and close this thread, but feel free to post any follow-up questions you might have as you explore your backups.
