### ISSUE TITLE
Error in https://hesweb.dev/files/game-simulators/war.php

### ISSUE THREAD

**Issue by philyuska** [susanBuck/e2-fall19#26]
When i click on the link for the [war simulator](https://hesweb.dev/files/game-simulators/war.php), it is throwing an error : __`Parse error: syntax error, unexpected end of file in /home/forge/hesweb.dev/public/files/game-simulators/war.php on line 44`__

**Comment by susanBuck** [comment]
Hey @philyuska - Thanks for the heads up! Just fixed it.

Here's what was wrong:

In my code, I had accidentally used what's called a short php open tag; it looks like this:

`<?`

Compare that to the normal PHP open tag:

`<?php`

My local server is configured to allow the short open tag, so it didn't throw any errors in testing.
On production, however, the server is not configured to allow short open tags which is why it threw in an error.

Two takeaways here:

1. Sometimes configurations in your servers can cause unexpected discrepancies in how your code runs locally vs. on production.
2. It's good to double check your work on production in case there are such discrepancies (something I apparently failed to do :)


Reference:
+ [PHP.net tags - where it discusses the short open tag](https://www.php.net/manual/en/language.basic-syntax.phptags.php)
+ Supplemental course notes on [PHP configs](https://hesweb.dev/e2/notes#/appendix/php-configs) where one could adjust their settings to allow/disallow short open tags.
