### ISSUE TITLE
How to sum the values in the array

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e2-fall19#33]
I'm trying to sum the values in the array:
array [0, 1, 1, 0, 1];
desired outcome: 3;

Is it possible?
So far, I was able to calculate the number of array items using 'count($array)'

However, it doesn't give me the desired result:
outcome: 5;

**Comment by susanBuck** [comment]
Hi @anyav77 -

There is a built in function called [`array_sum`](https://www.php.net/manual/en/function.array-sum.php) that can help with this.

However, before you try using that, I suggest trying to tackle this "manually" because it's good practice...

You could use a `foreach` loop to iterate through the values in the array, adding each value as you go.

Example in "pseudo-code":

```php
Start `total` at 0
For every value in the array...
    total = total + value
```

**Comment by susanBuck** [comment]
Closing this thread due to inactivity, but feel free to re-open or start a new thread is this question is still pending.
