### ISSUE TITLE
 VirtualHost/Subdomain setup - 000-default.conf does not exist

### ISSUE THREAD

**Issue by tasneemmunshi** [susanBuck/e2-fall19#5]
Hi Susan & Class,

I am currently on the lecture notes section of "VirtualHost/Subdomain setup" - so far everything has executed and worked out fine up until this point (I have been following the steps on my own as the videos have been playing simultaneously).

When I am trying to configure so that a subdomain can point to a different document root, it's not working out as explained in the notes and I am not sure why - the part that seems to be different on my end is when I am using VirtualHost configuration and trying to complete via opening/updating the config file:  /etc/apache2/sites-enabled/000-default.conf

When I open the above in nano - the file displays completely blank, see first screenshot (whereas in the lecture, I notice that there is already a content block ([original block](https://gist.github.com/susanBuck/790ea5a0d1ad7d02e586)).  

I have tried inserting this original text in there, followed by the VirtualHost block we had to paste in there and then updating the ServerName piece to my server name (practice.tasneemmunshi.xyz), then trying to save - when I attempt to save, I receive the following error (screenshot also provided below):  **Error writing /etc/apache2/sites-enabled/000-default.conf: No such file or directory**

I have tried many times - and can't seem to backtrack where I might have made an error.  Any insight/assistance would be greatly appreciated!  

Thank you.
Tasneem

![Screenshot 1](https://user-images.githubusercontent.com/54759686/64820157-cf79b900-d57d-11e9-9093-d6ae5d1ac382.png)

![Screenshot 2](https://user-images.githubusercontent.com/54759686/64820536-9e4db880-d57e-11e9-98d3-3bc5796d2c55.png)

**Comment by janenycxo** [comment]
When i received a similar error, I tried to troubleshoot until I found the file saved under another directory. Could you have saved it somewhere else?

**Comment by tasneemmunshi** [comment]
Hi @susanBuck - I just emailed you the new password/info you requested to help investigate!  Thank you for your help!

- Tasneem

**Comment by susanBuck** [comment]
Confirming receipt! Taking a look now and will follow-up with what I find out shortly.

**Comment by susanBuck** [comment]
Follow-up: I forgot that by default the DO servers don't allow login via passwords, so I was unable to log into your server despite having the password.

As a work around, I'm going to have you add one of my SSH keys to your server, so I can login via the keys instead of a password.

To do this, while SSH'd into your server, edit your SSH `authorized_keys` file with nano:

```bash
nano ~/.ssh/authorized_keys
```

To begin with, you should see your existing key:

![image](https://user-images.githubusercontent.com/237711/64910553-98261c00-d6e5-11e9-85d0-23fa0d58484d.png)

After your key, on a new line, [paste in my key which you can find here](https://hesweb.dev/e2/notes#/production-server/student-key)

(Make sure you copy the entire line, starting with `ssh-rsa AAAAB3Nz...` and ending with `...vKIX susanbuck@fas.harvard.edu`)

After you paste it in, it should look like the following and you can save/exit nano.

![image](https://user-images.githubusercontent.com/237711/64910652-9b6dd780-d6e6-11e9-9c2c-f1d6ef04292d.png)

Once you've done this, let me know and I'll test that I can log in.

__Footnotes on security:__
This is a public forum in which I'm sharing my SSH key info. However, I'm not concerned about it because:
+ a) Nothing on our course servers is of high priority, and the chances of some random internet stranger trying to use this post to hack in is super, super low.
+ b) I shared the actual key via the course notes  site, which only authenticated students have access to.
+ c) Even if someone got the public key, they still wouldn't have the corresponding private key that's on my computer

**Comment by tasneemmunshi** [comment]
Hi @susanBuck - just completed the above set of steps... all done, please test :)

**Comment by tasneemmunshi** [comment]
Hi Susan! Just wanted to let you know that I was able to resolve the above issue somehow and everything executed fine! Will keep you posted on any further issues. Thanks again for your help! :)

**Comment by susanBuck** [comment]
Ok, cool - glad you got it sorted out! :-)
