### ISSUE TITLE
Composer: Edit Path Variable- Windows Link Broken

### ISSUE THREAD

**Issue by shcantrell** [susanBuck/e2-fall19#53]
Hello,

I was trying to add the `c:\xampp\php\` to my computer's *PATH* variable, but the link to the instructions is returning a 404 error.

Heeeeeelp.

**Comment by shcantrell** [comment]
Oh - I was looking at the Mac instructions and the Windows instructions are included there.

Sorry about that.

**Comment by susanBuck** [comment]
Just added a "Jump to" link at the top of that note set to emphasize there are different instructions on the same page. It can be confusing because you're coming there from the "Composer" instructions which has a separate page for mac vs. windows.

![image](https://user-images.githubusercontent.com/237711/67688241-e29ae980-f96f-11e9-9874-7f740d17c746.png)

**Comment by shcantrell** [comment]
Lol - it's always Monday's fault!
