### ISSUE TITLE
PHP Path Doesn't Change

### ISSUE THREAD

**Issue by chantelledmello** [susanBuck/e2-fall19#55]
Hi Prof,

I'm having some issues with changing my php PATH in Terminal. At first attempt, when I ran `which php`,  I got `/usr/local/php5/bin/php` as my path. 

I proceeded to follow the instructions in the notes to edit my `/etc/paths` file and add the path to the XAMPP bin folder. When I ran `echo $PATH` again, I noticed that `/Applications/XAMPP/xamppfiles/bin` had been added to my path, but that it still shows me the old location when I run `which php`. 

I've closed an opened Terminal numerous times to no avail. 

Not sure how to remedy this so am attaching a screenshot below for reference. 

<img width="488" alt="Screen Shot 2019-10-28 at 8 05 45 PM" src="https://user-images.githubusercontent.com/26146422/67727010-29173500-f9be-11e9-964f-947040ce9957.png">

**Comment by susanBuck** [comment]
Hi @chantelledmello -

Edit your paths file again and remove the path to `/usr/local/php5/bin` -- because it's listed first it's taking precedence over the path you actually want to use.

After you make those changes, save, restart Terminal and see if that fixes things.

**Comment by susanBuck** [comment]
Follow-up because I just thought of something:

If `/usr/local/php5/bin` is not in your `/etc/paths` file, it's possible it's being added from some other source.

If that's the case, examine the following files (if they exist) to see if they have any reference to `/usr/local/php5/bin`:

+ `~/.bash_profile`
+ `~/.bashrc`
+ `~/.profile`

If so, delete any lines in those files with that reference.

**Comment by chantelledmello** [comment]
I had a mention of it in my `~/.bash_profile`. Removing it fixed the path right away. Thanks heaps!

**Comment by susanBuck** [comment]
Glad that did the trick!
