### ISSUE TITLE
Project 3 Peer Review: Undergrads earn/be penalized if we participate?

### ISSUE THREAD

**Issue by jeremiahazurin** [susanBuck/e2-fall19#56]
I'm undergrad. If undergrads choose to participate, does that mean undergrads can earn or be penalized for credit? In other words, if undergrads earn a "poor" grade based on the low number of points, will this hurt us? I'm assuming not bc even if we earn 1-6 points, then that's somewhat "extra credit"? 

Or will we just not earn credit altogether if undergraduates complete this?

Thank you! Really enjoying this course.

**Comment by susanBuck** [comment]
Hi @jeremiahazurin -

I just checked the roster and everyone, including you, is listed as taking this course for "Graduate" credit. I guess it's possible to be an undergrad but take a course for Graduate credit?

As for how it would work *if* you were a student taking the course for Undergraduate credit *and* you opted in *and* you scored below 10/10 - I'd just record it as 10/10 so it didn't penalize you.

**Comment by jeremiahazurin** [comment]
Hmm, interesting. Thank you for that clarification. It seems that I’m at a crossroad:

As an undergraduate degree candidate in the HES, the assignment is optional.
But as an undergraduate apparently registered for grad credit, the assignment is required.

Where do I go from here? 
Thanks again!

Sincerely, 
Jeremiah Azurin
azurinj@gmail.com <mailto:azurinj@gmail.com>

**Comment by jeremiahazurin** [comment]
Nevermind, I can only benefit from it so I'll do it. I think because I'm reg for grad credit that I technically fall under the second group, too.

Thanks again!

**Comment by susanBuck** [comment]
I agree that because you're registered in *this* course for grad credit, you're required to do it. 

In the ["Work and Grading" section about Graduate credit](https://hesweb.dev/e2/work-and-grading#Graduate%20credit), I explicitly state *"taking this course for graduate credit"*:

> Students **taking this course for graduate credit** will be required to do a peer review round on one of the projects (details TBA in lecture).

Same thing on the [peer review spec](https://hesweb.dev/e2/projects/3pr):

> While every student is encouraged to participate in this peer review exercise, only **students taking this course for graduate credit are required to participate**. If you are taking this course for undergraduate credit and wish to opt out from this assignment, simply note this in the comment box when completing the Project 3 Peer Review submission in Canvas.

*"taking the course for graduate credit"* is the language the HES admins gives instructors when it comes to this requirement, so I think that's in line with their expectations as well. 

Regardless, I'm glad you decided to complete it - I think it can be a really useful exercise.
