### ISSUE TITLE
rock-paper-scissors: Errors When Requiring with Composer

### ISSUE THREAD

**Issue by MPVaccaro** [susanBuck/e2-fall19#64]
I have Composer working properly in my command line.  I am using a Mac. I created a new **_week8_** folder that included only the ```composer.json``` file.  When I typed in ```composer require susanbuck/rock-paper-scissors``` I got exception and cache errors.  I looked into the issues forum, and found the cache problem.  I then attempted to use the ```sudo chmod 777 cache``` statement in the **_week8_** directory, and it did not help. I received the message ```No such file or directory``` then when I tried again to require rock-paper-scissors,  I received the same error messages as before.  The last round of errors is  copied below:

``` 
Marys-MacBook-Pro-3:week8 maryvaccaro$ sudo chmod 777 cache
Password:
chmod: cache: No such file or directory
Marys-MacBook-Pro-3:week8 maryvaccaro$ 
Marys-MacBook-Pro-3:week8 maryvaccaro$ composer require susanbuck/rock-paper-scissors
Cannot create cache directory /Users/maryvaccaro/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /Users/maryvaccaro/.composer/cache/files/, or directory is not writable. Proceeding without cache

PHP Warning:  preg_split(): JIT compilation failed: no more memory in phar:///usr/local/bin/composer/vendor/symfony/console/Application.php on line 1091

Warning: preg_split(): JIT compilation failed: no more memory in phar:///usr/local/bin/composer/vendor/symfony/console/Application.php on line 1091
PHP Warning:  preg_replace(): JIT compilation failed: no more memory in phar:///usr/local/bin/composer/vendor/symfony/console/Formatter/OutputFormatter.php on line 36

Warning: preg_replace(): JIT compilation failed: no more memory in phar:///usr/local/bin/composer/vendor/symfony/console/Formatter/OutputFormatter.php on line 36
                                                        
  [ErrorException]                                      
  preg_match(): JIT compilation failed: no more memory  
                                                        

PHP Warning:  preg_match_all(): JIT compilation failed: no more memory in phar:///usr/local/bin/composer/vendor/symfony/console/Formatter/OutputFormatter.php on line 199

Warning: preg_match_all(): JIT compilation failed: no more memory in phar:///usr/local/bin/composer/vendor/symfony/console/Formatter/OutputFormatter.php on line 199
require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

Marys-MacBook-Pro-3:week8 maryvaccaro$
```

**Comment by susanBuck** [comment]
The `sudo chmod 777 cache` command is only relevant once you've created a `e2framework` project where a `cache` directory will exist. 

If you're starting with an empty `week8` folder, that command will not do anything since no `cache` directory will exist.

The "cache" message you're actually getting is not about a `cache` directory in your project/directory - it's about Composer's master cache directory (`/Users/maryvaccaro/.composer/cache/`). Example:

```
Cannot create cache directory /Users/maryvaccaro/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. 
Proceeding without cache
```

This message just means that Composer won't be able to write any cache files, but, as it notes, it will *Proceed without cache*. It'll still work, Composer just can't be as efficient as it could be if it had access to its cache. You can ignore the message, or if you want to fix it, you can run this command:

```bash
sudo chown -R $USER $HOME/.composer
```

The next message you're getting about **JIT compilation failed: no more memory** *does* need to be resolved in order to move forward.

A classmate brought this to my attention earlier today - post #63.

The fix is to open your XAMPP php.ini file:

```
nano /Applications/XAMPP/xamppfiles/etc/php.ini
```
At the bottom, add the following line:

```
pcre.jit=0
``` 
Save your changes and exit.

Attempt the Composer command again, which in your case is:

```
$ composer require susanbuck/rock-paper-scissors
```

**Comment by MPVaccaro** [comment]
Thank you!  I did both steps as listed above and it solved the problem.

**Comment by susanBuck** [comment]
@MPVaccaro Great; glad that did the trick!
