### ISSUE TITLE
Accessing index.php from main directory

### ISSUE THREAD

**Issue by chantelledmello** [susanBuck/e2-fall19#69]
A quick Q about why I'm still getting this error when I try to access the site via its long-tail URL - ```http://localhost/e2/practice/zipfoods/public/index.php``` but am able to load the site perfectly fine when I use ```http://zipfoods.loc```

<img width="1438" alt="Screen Shot 2019-11-05 at 6 27 48 PM" src="https://user-images.githubusercontent.com/26146422/68251556-c9daa580-fff9-11e9-98e9-bf2641827323.png">

**Comment by susanBuck** [comment]
The application is set up in such a way that it expects to be served with the `public` directory as the document root. It does this for security purposes - to limit the amount of files the browser has access to.

If you attempt to visit the site directly via `http://localhost/e2/zipfoods/public`, then you are bypassing that setup.

To understand why this happens, take a look at [public/index.php](https://github.com/susanBuck/e2/blob/master/zipfoods/public/index.php) (which is the entry point to the application.

Note how it sets up a constant called DOC_ROOT that is set relative to the results of `$_SERVER['DOCUMENT_ROOT']`:

```php
define('DOC_ROOT', $_SERVER['DOCUMENT_ROOT'].'/../');
```

This is key: The `$_SERVER['DOCUMENT_ROOT']` super global **retrieves the current document root.**

When the app is running/configured correctly, e.g. you're accessing it via `http://zipfoods.loc`, the `DOC_ROOT` is correctly set to `"/path/to/htdocs/e2/zipfoods/public/../"`

If, however, you bypass the local domain, then you're using the document root for http://localhost, and as a result `DOC_ROOT` is set to `"/path/to/htdocs//../"`.

This will then produce an error in the next line that attempts to load the composer autoload file using DOC_ROOT:

```php
require DOC_ROOT.'/vendor/autoload.php';
```

Because instead of translating to something like this (RIGHT):
```php
require '/path/to/htdocs/e2/zipfoods/public/../vendor/autoload.php';
```

It translates to something like this (WRONG):
```php
require '/path/to/htdocs//../vendor/autoload.php';
```


## Why is it set up this way?
As noted above, it's set up this way for security purposes. We want to limit the browser to only have access to the `public/` directory, restricting access to the server-specific files one level up.

Think back to the metaphor I gave in lecture last week - I said `/public` is like the front of a store, and the place you want to restrict your visitors (via the browsers to).

By trying to access the project directly via `http://localhost` and `/public`, it's the equivalent of customers trying to enter the store by walking in through the back employee entrance.

**Comment by susanBuck** [comment]
Closing this post due to inactivity, but feel free to continue the discussion or post a new thread if any questions are still pending.
