### ISSUE TITLE
Validation error - looking for confirmationName

### ISSUE THREAD

**Issue by Janeece** [susanBuck/e2-fall19#88]
When I validate the entries in my form, I keep getting a Fatal Error. I believe it's looking for the id to create a confirmationName. I've tried to have it not go to that part of the code, but have been unsuccessful in figuring it out.

The other problem I had was with the formatting of the form. When I extended templates.master, it placed the zipfoods image below the form. Since I couldn't figure out why that was happening, I just removed it.

The data is being added to the database. So that's win.

Here is a link to the code:
https://github.com/Janeece/e2/commit/7d8a4b37df751f1adce1d3f45c957728c3327136

Thanks!

**Comment by susanBuck** [comment]
@Janeece - I ran your code locally and got this error:

```
Fatal error: Uncaught Error: Call to undefined method E2\Validate::numeric(10,2)() in /Users/Susan/Sites/hes/dwa-bash/students/e2/zipfoods/vendor/susanbuck/e2core/src/Validate.php:40 
```

And here's the relevant code:
```php
$this->app->validate ([
           'name' => 'required|alphaNumeric',
           'description' => 'required|minLength: 200',
           'price' => 'required|numeric(10,2)',
           'available' => 'required|digit',
           'weight' => 'requried|numeric(10,2)',
           'perishable' => 'required|tinyint(1)',
       ]);
```

The error is saying `Validate::numeric(10,2)` is not found. This is because the rule should just be `numeric`; the `numeric` rule has no parameters.

When I fixed that error, the next error reported:

```
Fatal error: Uncaught Error: Call to undefined method E2\Validate::requried() in /Users/Susan/Sites/hes/dwa-bash/students/e2/zipfoods/vendor/susanbuck/e2core/src/Validate.php:40
```

Just a typo there - `requried` should be `required`.

Next error:
```
Fatal error: Uncaught Error: Call to undefined method E2\Validate::tinyint(1)() in /Users/Susan/Sites/hes/dwa-bash/students/e2/zipfoods/vendor/susanbuck/e2core/src/Validate.php:40 
```

This is because there is no `tinyint(1)` validation rule. Refer to the list of available rules: https://hesweb.dev/e2/notes#/php/e2framework/forms?jump=available-validation-rules.

After I fixed that, and ran a test with valid data, I was able to confirm the data was being added to the database.

**Comment by Janeece** [comment]
Thank you for looking into this and responding so quickly.

Janeece
