### ISSUE TITLE
Uploading to Server

### ISSUE THREAD

**Issue by lindsaymshepard** [susanBuck/e2-fall19#9]
At first, it loaded just the Digital Ocean line we wrote, but then I refreshed it and it is saying page not found.  But, before when it loaded the first time it did not load the code in my index.php file. I'm not sure if I missed a step, but I rewatched the videos and followed the notes when completing the project.

**Comment by susanBuck** [comment]
Hi @lindsaymshepard -

Can you be a bit more specific?
Not sure what you mean by "it" or which specific DigitalOcean line you're referring to.

Please describe clearly what steps you're attempting and how they're differing from what you're expecting. Include screenshots, relevant IP addresses, and any other supporting details that can help us help you. : )

**Comment by lindsaymshepard** [comment]
Sorry I should have clarified more! I am on part 2b on the summary notes. I have followed steps up to 2a, but when I tested my p1.lindsayshepard.me address it says page 404 not found. I think a better questions for 2b is where am I putting this:

Step 2b. Local domain - hosts routing
Edit your computer’s hosts file to register this new domain.
Mac: /private/etc/hosts
Windows: c:\Windows\System32\drivers\etc\hosts
Example:
127.0.0.1 appname.loc

when I type this in command line it says permission denied

**Comment by susanBuck** [comment]
Excellent - those extra details really help - thanks @lindsaymshepard!

Note that [Step 2a. Local domain - VirtualHost](https://hesweb.dev/e2/notes#/production-server/summary?jump=step-2a-local-domain-virtualhost) is specific to your **local domain**, so it should not have any effect on your production domain, p1.lindsayshepard.me.

Regarding [Step 2b. Local domain - hosts routing](https://hesweb.dev/e2/notes#/production-server/summary?jump=step-2b-local-domain-hosts-routing): your computer's host file is an admin protected file. For full details on this step and how to edit this admin file, return to the [primary notes on local domains](https://hesweb.dev/e2/notes#/local-server/local-domains?jump=step-3-create-a-new-host) and read the section on editing your hosts file for full instructions.

Specifically, you'll note it says that in order to edit your hosts file, you'll need to prefix your command with `sudo` (if on a Mac) or `elevate` (if on Windows).

**Comment by lindsaymshepard** [comment]
So because it's just my local domain in Step 2a, its ok that at this point my pi.lindsayshepard.me is loading 404 page not found?

**Comment by lindsaymshepard** [comment]
Do I run those commands under the root folder in digital ocean on terminal or on my second tab which is just in the htdocs folder?

**Comment by susanBuck** [comment]
Correct - the production domain (p1.lindsayshepard.me) and local domain are independent from one another. Until you get to [Step 5. Production domain - VirtualHost](https://hesweb.dev/e2/notes#/production-server/summary), you shouldn't expect the production domain to work. 👍

To answer your second question - It sounds like you have the following in Terminal:
Tab 1 is connected to digitalocean
Tab 2 is in the htdocs folder on your computer.

In this instance, you're trying to configure the local domain on your computer. Specifically, you're trying to edit the hosts file on your computer. Because of that, you should run the command in Tab 2.

**Comment by susanBuck** [comment]
On a side note - the steps on the [Summary page](https://hesweb.dev/e2/notes#/production-server/summary) are quite terse, and really only useful as a refresher/quick reference for paths to specific files, commands, etc.

While you're still learning/getting comfortable with the process, I suggest following along with the primary notes (and lecture videos) on each individual steps, because it's broken down in more detail there.

**Comment by lindsaymshepard** [comment]
Thank you, I seems o be having issues still, but I am rewatching the lecture videos now to try to figure out how to get it turned in! The html part was easy I just am having issues with where to place things in the command line.

**Comment by lindsaymshepard** [comment]
I am not sure if possible, but because I have done some steps and not others I am very lost. Is it possible to have a zoom session to help me back out of what I've done and get it uploaded?

**Comment by susanBuck** [comment]
Sure - we can do a Zoom session and get you on track. I'm available all today - when would be good for you?

**Comment by lindsaymshepard** [comment]
That would be great! I am available now- as well as through the rest of the day.

**Comment by susanBuck** [comment]
Ok - here's my zoom meeting room URL: https://harvard-dce.zoom.us/j/6503342434

**Comment by lindsaymshepard** [comment]
Great- I'm joining now!
