### ISSUE TITLE
Unable to run migration console command after production database setup

### ISSUE THREAD

**Issue by tasneemmunshi** [susanBuck/e2-fall19#90]
Hi there - after my production database is setup, I am having an issue running console command for migration (please see 'error message' that pops up upon attempting to complete this step), see screenshot below.  Not sure why this is happening as I've followed each step via the video... kindly advise, thank you!

![Screen Shot 2019-11-26 at 7 17 21 PM](https://user-images.githubusercontent.com/54759686/69683111-95e72300-1081-11ea-8bab-4a621babd761.png)

**Comment by RGPhD** [comment]
Hi @tasneemmunshi,

I see the code references your ```console``` and your ```.env``` file.  Did you follow the directions from the notes for both setting up the commands and setting up the console at <https://hesweb.dev/e2/notes#/php/frameworks/commands?jump=set-up-console>, as well as Video Week 12, Part 4 and Video Week 12, Part 5?  I do not see the Commands file in your controller code.  I also do not see the env updates in your AppController file.  

Futher, you might want to push your zipfoods code on github and run ```composer update``` locally and ```composer install --no-dev``` on production to get all of the e2framework updates made by Professor Buck.  I do not see any code pushed to github or updates to your zipfoods folder for the last 16 days.

That is all I can tell is missing; I will look at it more tomorrow if you have not got it working by then :)

Robelyn

**Comment by susanBuck** [comment]
Piggy-backing on @RGPhD's notes: Looking at your [zipfoods directory](https://github.com/tasneemmunshi/e2/tree/master/zipfoods), I don't see a `console` file.

**Comment by tasneemmunshi** [comment]
thank you both @RGPhD and @susanBuck - taking a look, will revert back with any further questions.

**Comment by tasneemmunshi** [comment]
@RGPhD @susanBuck I ran through week 12 videos again (video 4 and 5 as recommended), and all went well and I also did a code push for my zipfoods folder on github so everything is current.. everything went well up until the same point of running the console command for migration - see screenshot below for the error that popped up. I'm not sure where I am incorrectly executing the steps, as I followed everything step by step per the videos and notes... the error message is indicating an undefined method in the console file, however as I just stated, I copied and followed the instructions/notes as outlined in the videos and notes section so I am really confused as to where and why the issue is occurring... thank you both!

![Screen Shot 2019-12-01 at 8 57 49 PM](https://user-images.githubusercontent.com/54759686/69925351-acc0b780-147d-11ea-8736-fad8b5dd57bc.png)

**Comment by susanBuck** [comment]
@tasneemmunshi - Can you confirm you ran `composer install --no-dev` in your zipfoods directory on production? This step is needed to make sure all your dependencies are up to date ([ref](https://hesweb.dev/e2/notes#/php/composer-deployment?jump=deploy)).

The error message it's showing indicates it's trying to locate a method `console` within the app instance, and it says it does not exist. This would be the case if you were running an older version of the framework which did not yet have the `console` feature added.

If you run `composer info` it will show you what dependencies/versions you currently have installed. As of this writing, the latest version of `susanbuck/e2core` is 0.1.8 so that should be the version number you see.

Example:
```
root@e2:/var/www/html/e2/zipfoods# composer info
Do not run Composer as root/super user! See https://getcomposer.org/root for details
[...other dependencies listed here...]
susanbuck/e2core              0.1.8   Practice framework for CSCI E-2
[...other dependencies listed here...]
```

If you see anything less than that, run `composer install --no-dev` to bring everything up to date.

**Comment by tasneemmunshi** [comment]
Hi @susanBuck - you're definitely right about the latest version needing to be installed, I checked for the current dependencies/versions and it's not current.  However, upon running 
`composer install --no-dev`, I am receiving a message noting that there's nothing to install or update - any idea?  please see screenshot:
![Screen Shot 2019-12-02 at 2 35 52 PM](https://user-images.githubusercontent.com/54759686/69989319-63ba4300-1511-11ea-8e94-d7e2ed0adc64.png)

**Comment by susanBuck** [comment]
Hi @tasneemmunshi - 

I suspect maybe your local dependencies are also out of date, which is why the production version is out of date.

Recall that it works like this:
+ Locally you run `composer update` and it grabs the latest versions within the ranges specified in `composer.json`. The actual version numbers it downloads are recorded in `composer.lock`.
+ `composer.lock` gets sync'd to Github, then pulled to production where you run `composer install --no-dev` which will read from `composer.lock` to grab the appropriate version numbers (i.e. the same version numbers that were used locally).

If you haven't run `composer update` locally in a while, it likely has outdated versions there.

To fix:
1. Run `composer update` locally
2. Commit/push all changes (most importantly, changes to `composer.lock`)
3. On production, pull down the latest changes then run `composer install --no-dev`

Give that a shot and see if it fixes things.

**Comment by susanBuck** [comment]
Just had a follow-up thought: If `php console...` is working locally, then your dependencies there are probably up to date. In that case, it could just be that `composer.lock` was not sync'd to production with the latest version numbers?

**Comment by tasneemmunshi** [comment]
Thanks @susanBuck - that did it! All is now executing correctly, thank you for your patience and efforts in helping me troubleshoot!

**Comment by susanBuck** [comment]
np! Glad it's sorted out.
