### ISSUE TITLE
Converting a form item to a "tinyint" in the Database

### ISSUE THREAD

**Issue by MPVaccaro** [susanBuck/e2-fall19#93]
I added a new form to my Zipfoods project that accepts new product input, saves it to the database and displays the new product at the top of the "Products" page.  

The problem is I can't get the input for the "Perishable" selection in the form to input to the database.  I can see that the form is registering the input as either "1" or "2", but the database still records "null."

I have tried several ways, from Radio Buttons to Number inputs, all with the same result.  

This is my current form input:

```
<div class='form-group'>
            <label for='perishable'>Perishable? Enter 1 for Yes or 0 for No</label>
            <input type='number' min='0' max='1' step='1' class="form-control" name='perishable' id='perishable' value='{{ $app->old("perishable") }}'>
</div>
```

My Github repository is: [Mary's Zipfoods Github Repository](https://github.com/MPVaccaro/e2/tree/master/zipfoods)

My Production site is: [Mary's Zipfoods Production Site](http://zipfoods.junkpileart.com/)

__Note: The link to the add a new product form is at the bottom of the "Products" list.__

**Comment by susanBuck** [comment]
Hi @MPVaccaro 

At first glance, I suspect it might be a data type issue - whenever you get input data from a form, it's always a String - even if it's a numerical value such as 0... it will be "0".

Because your database is expecting an integer, this causes an error.

To address, try casting the perishable input value to an integer like so:
```php
$perishable = (int)$this->app->input('perishable');
```

If this doesn't work, let me know; I'll clone your app locally and test it on my end.

Ref: https://www.php.net/manual/en/language.types.type-juggling.php

**Comment by MPVaccaro** [comment]
Thank you! That solved it!

My question is: Why didn't I have that problem with ```price```, ```available``` and ```weight```?

_(At one point, I went into the database and changed the "perishable" data type from ```tinyint```to ```int,``` and the problem with "perishable" was unchanged.  Then I changed the data type back to tinyint.  Since that didn't solve it, I don't think that was the cause of this problem.)_

So now I'm trying to understand why this problem didn't appear with the other database ```int``` inputs in the "price," "available," and "weight" columns.

**Comment by susanBuck** [comment]
Hi @MPVaccaro - Had a chance to take a closer look at this...

I take back my original post above - I don't think it was a data type issue, because I just ran some tests and was able to successfully insert the numerical values from the form into the database without any type conflicts, and without the need to cast data types. 

Also, I ran your code both with the casting:
```
$perishable = (int)$this->app->input('perishable');
```

And without the casting:
```
$perishable = $this->app->input('perishable');
```

And they both worked the same. Perplexing!

If you take away `(int)` on your end, does it still fail?

**Comment by MPVaccaro** [comment]
This is strange - now it is working without the ```(int)``` casting!

I tried it so many ways originally, even changing the datatype on the database, and it kept recording ```null```. Then I casted it as you described and the problem was solved. What I couldn't understand is why this was a problem, as the other inputs worked fine.

I just now re-did the test, I removed the ```(int)``` casting, kept the database data type as ```tinyint``` and it worked correctly.

Could this have been a cache issue?

After reading your debugging note, **_(Quick tip: Debugging views #86)_** I've been examining and clearing cache in my new p4 project, and it has solved some _"mysterious and unsolveable"_ problems.

Also, restarting the XAMPP servers seems to help occasionally.

As a beginner, when I am making so many coding mistakes, which are then compounded with my own coding typos, it's hard to remember that sometimes all that's needed is a _"reset"_.

Could this have been one of those times?

**Comment by susanBuck** [comment]
I can't think of any cache-related things that might have caused this - but, as they say - "never say never". : )

I suspect you were doing a lot of debugging/shuffling things around. It's possible something changed between point A of it not working and point B of it working that you just lost track of. I know it's happened to me before. Sometimes I can backtrack and figure out what I changed that fixed it...other times it remains a mystery that can only be solved with a time machine. : )

**Comment by susanBuck** [comment]
Going to go ahead and close this thread out, but feel free to start a new thread if the bug reappears!
