### ISSUE TITLE
extend the “app” object supplied in the E2 framework?

### ISSUE THREAD

**Issue by philyuska** [susanBuck/e2-fall19#95]
Is it possible to extend the “app” object supplied in the E2 framework?

There are a couple of methods that I would like to share within my project and if I have time I would like to attempt to do so.

For example I am finding it necessary to persist some of my object data in session variables like the deck of cards being used in the game and I would like be able to share the ability to destroy the entire array key in $_SESSION e.g.

```php
 public function unsetSession($key)
{
    if (!isset($_SESSION)) {
        session_start();
    }

    if (isset($_SESSION[$key])) {
        unset($_SESSION[$key]);
    }
}
```
Is it possible to bind multiple parent objects or would I need to use a wrapper around my controller class containing the methods I would like to share?

**Comment by susanBuck** [comment]
Hi @philyuska - 

Technically, you could extend the `app`. You'd do this by creating your own class (let's call it `MyApp`) that extends `E2\App`.

Then, in `public/bootstrap` and `/console.php` instead of this:

```php
# Initialize App object
$app = new \E2\App();
```

You'd have this:

```php
# Initialize App object
$app = new MyApp();
```

I would only go this route if there were methods within `E2\App` that I wanted my child class to be able to harness and/or overwrite. If not, I'd choose one of the following approaches:

Because all controllers extend the base controller at `/app/Controllers/Controller.php`, you can put any shared methods in that class.

Or, you could create a class similar to [`/app/Products.php`](https://github.com/susanBuck/e2/blob/master/zipfoods/app/Products.php). Maybe it's called something more generic like `Util` (short of Utilities), and it can take advantage of [static methods](https://hesweb.dev/e2/notes#/php/inheritance-visibility-static?jump=static-keyword).

For the method you'd describe, I'd probably go with the last approach.

Let me know if you have any follow-up questions on this or run into roadblocks during implementation!

**Comment by susanBuck** [comment]
I got so wrapped up in answering your question about extending app, I forgot to mention that the app object may already have the functionality you're looking for!

Check out [sessionSet](https://hesweb.loc/e2/notes#/php/e2framework/app?jump=sessionset) and [sessionGet](https://hesweb.loc/e2/notes#/php/e2framework/app?jump=sessionget).

If you look at the underlying code ([ref](https://github.com/susanBuck/e2core/blob/master/src/App.php)), you can see they're effectively doing the same thing your method described above is doing. Here are the relevant methods:

```php
    /**
    * Get a session value
    */
    public function sessionGet(string $key, $default = null)
    {
        $this->sessionStart();
        return $_SESSION[$key] ?? $default;
    }
    /**
    * Set a session value
    */
    public function sessionSet(string $key, $value)
    {
        $this->sessionStart();
        $_SESSION[$key] = $value;
    }

    /**
     * Start the session if its not already started
     */
    private function sessionStart()
    {
        if (!isset($_SESSION) && $this->context == 'web') {
            session_start();
        }
    }
```

**Comment by philyuska** [comment]
Thank you, I think static methods may be exactly what i am looking for or at least the best first place to start.
